version: "3.3"  
services:
  frontend:
    image: ghcr.io/yonder-makers/weboffice-ui-svelte:latest
    environment:
      - API_URL=http://localhost:3000/
    ports:
      - "5000:5000"

  backend:
    image: ghcr.io/yonder-makers/weboffice-api:latest
    environment:
      - WEBOFFICE_URL=https://weboffice.yonder.local/
    ports:
      - "3000:3000"