name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Github docker
      run: |
        echo $CR_PAT | docker login ghcr.io -u yonder-makers --password-stdin
      env:
        CR_PAT: ${{ secrets.CR_PAT }}
    - name: Build docker image
      run: |
        docker build . --tag ghcr.io/yonder-makers/weboffice-ui-svelte:latest
    - name: Push image to Github container registry
      run: | 
        docker push ghcr.io/yonder-makers/weboffice-ui-svelte:latest
    
